name: flutter_video_player
description: "A Flutter Video Player App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http:
  path_provider: ^2.1.2
  video_player: ^2.8.3
  cupertino_icons: ^1.0.6
  intl_phone_field: ^3.2.0
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  get: 4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true